### ISSUE TITLE
Define what's included in a project

### ISSUE THREAD

**Issue by ErikAggie** [ttu-cs-5363-team-3/cs-5363-1#104]

**Comment by jsorbo** [comment]
Overall it looks good and I like having it in the wiki. I would just break the following out into new user stories in the backlog:

- Start time and end time
- Skills
- Causes - another list

**Comment by ErikAggie** [comment]
Updated with Jeff's suggestions. New issues opened, and those parts that won't be in Sprint 3 are marked with a '*'
