### ISSUE TITLE
Platform Document

### ISSUE THREAD

**Issue by jsorbo** [ttu-cs-5363-team-3/cs-5363-1#6]
Description of platform, IDE, frameworks, non-original artifacts and changes made, installation instructions,
configuration and compile instructions, running instructions, usernames/passwords needed or where to
obtain

**Comment by cademoor** [comment]
https://docs.google.com/document/d/1baD1ZKDUPuXRA7JHissRx8zetgZukt-fbGbPtWzbKXk/edit
